config/routes.rb
Rails.application.routes.draw do
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forms/product.rb
class Forms::Product < Product
  REGISTRABLE_ATTRIBUTES = %i(register code name price)
  attr_accessor :register
end

app/models/product.rb
class Product < ApplicationRecord
  validates :code, presence: true, uniqueness: true
  validates :name, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product_registration_form = ProductRegistrationForm.new
  end

  def create
    @product_registration_form = ProductRegistrationForm.new(product_registration_form_params)
    if @product_registration_form.save
      redirect_to :products, notice: "#{@product_registration_form.products.size}件の商品を登録しました。"
    else
      render :new
    end
  end

  private

  def product_registration_form_params
    params
        .require(:product_registration_form)
        .permit(products_attributes: Forms::Product::REGISTRABLE_ATTRIBUTES)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formobject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%= link_to '新規作成', new_product_path %>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>商品コード</th>
      <th>商品名</th>
      <th>販売価格</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.code %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%= link_to '一覧へ', products_path %>
<%= form_with(model: @product_registration_form, url: products_path, local: true) do |f| %>
  <%= render 'shared/error_message', object: f.object %>
  <table class="table">
    <thead>
    <tr>
      <th width="60px">登録</th>
      <th>商品コード</th>
      <th>商品名</th>
      <th>販売価格</th>
    </tr>
    </thead>
    <tbody class="bulk-registration-form">
    <%= f.fields_for :products do |ff| %>
      <tr class="item">
        <td class="text-center">
          <%= ff.check_box :register %>
        </td>
        <td>
          <%= ff.text_field :code, class: 'form-control' %>
        </td>
        <td>
          <%= ff.text_field :name, class: 'form-control' %>
        </td>
        <td>
          <%= ff.text_field :price, class: 'form-control' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= f.submit '一括登録', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_messages">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>